services:
  - type: web
    name: brollopsplaneraren
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false