# Generated by Django 6.0.6 on 2026-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='utgangsdatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
