# Generated by Django 6.0.6 on 2026-06-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profil_utgangsdatum'),
        ('planner', '0011_tidslinje_fotograf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunder', to='planner.photographer'),
        ),
    ]
