from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.checklist, name='checklist'),
    path('add/', views.add_checklist_item, name='add_checklist_item'),
    path('toggle/<int:item_id>/', views.toggle_checklist_item, name='toggle_checklist_item'),
    path('delete/<int:item_id>/', views.delete_checklist_item, name='delete_checklist_item'),
    path('budget/', views.budget, name='budget'),
    path('budget/add/', views.add_budget_post, name='add_budget_post'),
    path('budget/delete/<int:post_id>/', views.delete_budget_post, name='delete_budget_post'),
    path('budget/up/<int:post_id>/', views.move_budget_up, name='move_budget_up'),
    path('budget/down/<int:post_id>/', views.move_budget_down, name='move_budget_down'),
    path('budget/update/<int:post_id>/', views.update_budget_post, name='update_budget_post'),
    path('gastlista/', views.gastlista, name='gastlista'),
    path('gastlista/add/', views.add_gast, name='add_gast'),
    path('gastlista/update/<int:gast_id>/', views.update_gast, name='update_gast'),
    path('gastlista/delete/<int:gast_id>/', views.delete_gast, name='delete_gast'),
    path('gastlista/update/<int:gast_id>/', views.update_gast, name='update_gast'),
    path('gastlista/up/<int:gast_id>/', views.move_gast_up, name='move_gast_up'),
    path('gastlista/down/<int:gast_id>/', views.move_gast_down, name='move_gast_down'),
    path('leverantorer/', views.leverantorer, name='leverantorer'),
    path('leverantorer/add/', views.add_leverantor, name='add_leverantor'),
    path('leverantorer/toggle/<int:lev_id>/', views.toggle_leverantor, name='toggle_leverantor'),
    path('leverantorer/delete/<int:lev_id>/', views.delete_leverantor, name='delete_leverantor'),
    path('leverantorer/update/<int:lev_id>/', views.update_leverantor, name='update_leverantor'),
    path('leverantorer/up/<int:lev_id>/', views.move_leverantor_up, name='move_leverantor_up'),
    path('leverantorer/down/<int:lev_id>/', views.move_leverantor_down, name='move_leverantor_down'),
    path('tidslinje/', views.tidslinje, name='tidslinje'),
    path('tidslinje/add/', views.add_tidslinje, name='add_tidslinje'),
    path('tidslinje/delete/<int:tid_id>/', views.delete_tidslinje, name='delete_tidslinje'),
    path('tidslinje/update/<int:tid_id>/', views.update_tidslinje, name='update_tidslinje'),
    path('galleri/', views.galleri, name='galleri'),
    path('galleri/add/', views.add_bild, name='add_bild'),
    path('galleri/delete/<int:bild_id>/', views.delete_bild, name='delete_bild'),
    path('galleri/update/<int:bild_id>/', views.update_bild, name='update_bild'),
    path('fotograf/tidslinje/<int:kund_id>/', views.fotograf_tidslinje, name='fotograf_tidslinje'),
    path('fotograf/tidslinje/<int:kund_id>/ny/', views.fotograf_ny_handelse, name='fotograf_ny_handelse'),
    path('fotograf/tidslinje/<int:kund_id>/ta-bort/<int:handelse_id>/', views.fotograf_ta_bort_handelse, name='fotograf_ta_bort_handelse'),
    path('dashboard-embed/', views.dashboard_embed, name='dashboard_embed'),
    path('kop-planner/', views.checkout_planner, name='checkout_planner'),
    path('partner/intakter/', views.partner_intakter, name='partner_intakter'),
    path('whop/connect/', views.whop_connect, name='whop_connect'),
    path('whop/callback/', views.whop_callback, name='whop_callback'),
   
    # Partner/fotograf URLs
    path('partner/dashboard/', views.partner_dashboard, name='partner_dashboard'),
    path('partner/kunder/', views.partner_kunder, name='partner_kunder'),
    path('partner/kund/<int:kund_id>/', views.partner_kund_detail, name='partner_kund_detail'),
    path('partner/kund/<int:kund_id>/tidslinje/add/', views.partner_add_tidslinje, name='partner_add_tidslinje'),
    path('partner/kund/<int:kund_id>/galleri/add/', views.partner_add_galleri, name='partner_add_galleri'),
    path('partner/kund/<int:kund_id>/set-datum/', views.partner_set_brollopsdatum, name='partner_set_brollopsdatum'),
    ]