# Generated by Django 6.0.5 on 2026-05-16 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('12_manader', '12 månader innan'), ('6_manader', '6 månader innan'), ('3_manader', '3 månader innan'), ('1_manad', '1 månad innan'), ('veckan', 'Veckan innan'), ('dagen', 'Bröllopsdagen')], default='12_manader', max_length=20)),
                ('klar', models.BooleanField(default=False)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
