# Generated by Django 6.0.5 on 2026-05-16 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('lokal', 'Lokal'), ('catering', 'Catering'), ('fotograf', 'Fotograf'), ('film', 'Film'), ('blommor', 'Blommor'), ('klader', 'Klänning & Kostym'), ('musik', 'Musik & Underhållning'), ('transport', 'Transport'), ('inbjudningar', 'Inbjudningar'), ('ringar', 'Ringar'), ('har_och_makeup', 'Hår & Makeup'), ('ovrigt', 'Övrigt')], max_length=30)),
                ('beskrivning', models.CharField(blank=True, max_length=255)),
                ('budgeterat', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('faktiskt', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
