# Generated by Django 6.0.5 on 2026-05-16 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_budgetpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('antal', models.PositiveIntegerField(default=1)),
                ('svar', models.CharField(choices=[('invagen', 'Inväntar svar'), ('kommer', 'Kommer'), ('kommer_inte', 'Kommer inte')], default='invagen', max_length=15)),
                ('bord', models.CharField(blank=True, max_length=50)),
                ('notering', models.TextField(blank=True)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
