# Generated by Django 6.0.5 on 2026-05-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_gast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leverantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('fotograf', 'Fotograf'), ('film', 'Film'), ('florist', 'Florist'), ('musik', 'Musik & Underhållning'), ('catering', 'Catering'), ('lokal', 'Lokal'), ('transport', 'Transport'), ('klader', 'Klänning & Kostym'), ('har_makeup', 'Hår & Makeup'), ('inbjudningar', 'Inbjudningar'), ('ringar', 'Ringar'), ('ovrigt', 'Övrigt')], max_length=30)),
                ('kontaktperson', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('pris', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('bokat', models.BooleanField(default=False)),
                ('notering', models.TextField(blank=True)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
