# Generated by Django 6.0.5 on 2026-05-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_leverantor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tidslinje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.TimeField()),
                ('aktivitet', models.CharField(max_length=255)),
                ('plats', models.CharField(blank=True, max_length=255)),
                ('ansvarig', models.CharField(blank=True, max_length=100)),
                ('notering', models.TextField(blank=True)),
                ('ordning', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tid', 'ordning'],
            },
        ),
    ]
