# Generated by Django 6.0.5 on 2026-05-16 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_tidslinje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.URLField(max_length=500)),
                ('titel', models.CharField(blank=True, max_length=100)),
                ('kategori', models.CharField(choices=[('klanning', 'Klänning'), ('kostym', 'Kostym'), ('blommor', 'Blommor'), ('dukning', 'Dukning'), ('foto', 'Fotoinspiration'), ('hår_makeup', 'Hår & Makeup'), ('inbjudningar', 'Inbjudningar'), ('tårta', 'Tårta'), ('ovrigt', 'Övrigt')], default='ovrigt', max_length=20)),
                ('notering', models.TextField(blank=True)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-skapad'],
            },
        ),
    ]
