# Generated by Django 6.0.5 on 2026-06-04 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_galleri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brollop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=200)),
                ('datum', models.DateField(blank=True, null=True)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
                ('planerare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brollop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='budgetpost',
            name='brollop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='planner.brollop'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='brollop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='planner.brollop'),
        ),
        migrations.AddField(
            model_name='galleri',
            name='brollop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='planner.brollop'),
        ),
        migrations.AddField(
            model_name='gast',
            name='brollop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='planner.brollop'),
        ),
        migrations.AddField(
            model_name='leverantor',
            name='brollop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='planner.brollop'),
        ),
        migrations.AddField(
            model_name='tidslinje',
            name='brollop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='planner.brollop'),
        ),
    ]
