# Generated by Django 6.0.6 on 2026-06-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_brollop_budgetpost_brollop_checklistitem_brollop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Företagsnamn')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photographer_logos/')),
                ('primary_color', models.CharField(default='#FF0000', max_length=7, verbose_name='Primär färg (Hex-kod)')),
                ('whop_affiliate_id', models.CharField(max_length=100, verbose_name='Whop Affiliate ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
