# Generated by Django 6.0.6 on 2026-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='whop_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Whop E-post'),
        ),
    ]
