# Generated by Django 6.0.6 on 2026-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_photographer_whop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
