# Generated by Django 6.0.6 on 2026-06-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_tidslinje_fotograf'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='accent_color',
            field=models.CharField(default='#C7BDAE', max_length=7, verbose_name='Accentfärg (Hex-kod)'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='primary_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Navbar-färg (Hex-kod)'),
        ),
    ]
