# Generated by Django 6.0.6 on 2026-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_photographer_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logga (URL)'),
        ),
    ]
