# Generated by Django 6.0.6 on 2026-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_photographer_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetpost',
            options={'ordering': ['ordning', 'kategori']},
        ),
        migrations.AddField(
            model_name='budgetpost',
            name='ordning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
