# Generated by Django 6.0.6 on 2026-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_budgetpost_options_budgetpost_ordning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gast',
            options={'ordering': ['ordning', 'namn']},
        ),
        migrations.AddField(
            model_name='gast',
            name='ordning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
