# Generated by Django 6.0.6 on 2026-06-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_alter_gast_options_gast_ordning'),
    ]

    operations = [
        migrations.AddField(
            model_name='leverantor',
            name='ordning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
