# Generated by Django 6.0.6 on 2026-07-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_leverantor_ordning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Rubrik')),
                ('bio', models.TextField(blank=True, verbose_name='Kort presentation')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('website_url', models.URLField(blank=True, verbose_name='Hemsida')),
                ('custom_link_1_url', models.URLField(blank=True, verbose_name='Extra länk 1')),
                ('custom_link_1_text', models.CharField(blank=True, max_length=100, verbose_name='Text länk 1')),
                ('custom_link_2_url', models.URLField(blank=True, verbose_name='Extra länk 2')),
                ('custom_link_2_text', models.CharField(blank=True, max_length=100, verbose_name='Text länk 2')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_page', to='planner.photographer')),
            ],
        ),
    ]
