# Generated by Django 6.0.6 on 2026-07-16 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_partnerpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeverantorProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverantor_type', models.CharField(choices=[('jeweler', 'Ringförsäljare'), ('florist', 'Florist'), ('makeup', 'Makeup-artist'), ('venue', 'Lokal'), ('catering', 'Catering'), ('music', 'Musik/DJ')], default='jeweler', max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Företagsnamn')),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#F7F4EF', max_length=7)),
                ('accent_color', models.CharField(default='#C8A26B', max_length=7)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('accept_bookings', models.BooleanField(default=False, verbose_name='Ta emot bokningar')),
                ('booking_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email för bokningar')),
                ('whop_affiliate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leverantör',
                'verbose_name_plural': 'Leverantörer',
            },
        ),
    ]
