# Generated by Django 6.0.6 on 2026-07-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_leverantorprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Namn')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('booking_type', models.CharField(choices=[('consultation', 'Konsultation'), ('visit', 'Besök/Provning'), ('call', 'Videosamtal')], default='consultation', max_length=20)),
                ('date', models.DateField(verbose_name='Datum')),
                ('time', models.TimeField(verbose_name='Tid')),
                ('message', models.TextField(blank=True, verbose_name='Meddelande')),
                ('status', models.CharField(choices=[('pending', 'Väntar på bekräftelse'), ('confirmed', 'Bekräftad'), ('completed', 'Genomförd'), ('cancelled', 'Avbokad')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leverantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='planner.leverantorprofil')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
