# Generated by Django 6.0.6 on 2026-07-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='leverantorprofil',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
