# Generated by Django 6.0.6 on 2026-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_leverantorprofil_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='leverantorprofil',
            name='background_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bakgrundsbild (URL)'),
        ),
    ]
