# Generated by Django 6.0.6 on 2026-08-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_leverantorprofil_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='leverantor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_page', to='planner.leverantorprofil'),
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='photographer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_page', to='planner.photographer'),
        ),
    ]
