# Generated by Django 6.0.6 on 2026-08-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_partnerpage_leverantor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='snapchat_url',
            field=models.URLField(blank=True, verbose_name='Snapchat'),
        ),
    ]
