# Generated by Django 6.0.6 on 2026-08-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_partnerpage_snapchat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='background_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bakgrundsbild (URL)'),
        ),
    ]
