# Generated by Django 6.0.6 on 2026-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_photographer_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('bs', 'Bosnian')], default='sv', max_length=2, verbose_name='Språk'),
        ),
    ]
